### ISSUE TITLE
Boost.Python - Familiarity

### ISSUE THREAD

**Issue by jorgecfelix** [livelaughconquer/Automated-Planetary-Mapping-of-Mars#3]
Getting familiar with boost.python in order to extract processed image from C++ into a python numpy array.

**Comment by jorgecfelix** [comment]
Boost.Python library installation issues

**Comment by jorgecfelix** [comment]
Building Boost.Python library files for vc90 and Python 2.7

**Comment by md-aintright** [comment]
Currently testing out building boost/boost-python libraries on OSX
