### ISSUE TITLE
PyBrain - Familiarity

### ISSUE THREAD

**Issue by md-aintright** [livelaughconquer/Automated-Planetary-Mapping-of-Mars#32]
Getting familiar with PyBrain to implement neural network

**Comment by sebaqu11** [comment]
The switch to a better machine learning library is possible, for Pybrain lacks CNN support and the library development seems discontinued.  I am currently looking into the Lasagne library which seems more appropriate as it is well documented and is being actively developed.

**Comment by sebaqu11** [comment]
No longer using PyBrain, switched to Lasagne.
