### ISSUE TITLE
Integration of Python and C++

### ISSUE THREAD

**Issue by jorgecfelix** [livelaughconquer/Automated-Planetary-Mapping-of-Mars#8]
Create a Python module that will allow us to transfer image data from an OpenCV matrix into a Python numpy array.

**Comment by sebaqu11** [comment]
Add opencv include path as value to environment variable "INCLUDE" and add opencv_world310.lib to wherever %LIBPATH% is on your system.

**Comment by sebaqu11** [comment]
Starting this weekend (2/5), I will try to get Boost.Python working properly

**Comment by ktaed** [comment]
I was looking at the ndarray object and it looks like we may not need to wrap the numpy array inside an image object. I will work on the numpy exposure using the python/c api
